### ISSUE TITLE
shadow-cljs support broken in 2.10.+

### ISSUE THREAD

**Issue by thheller** [clojure-emacs/clj-suitable#15]
shadow-cljs 2.10.+ completely replaces all REPL implementations so the code used by clj-suitable no longer exists. It was never part of any official API so I didn't pay much attention to keeping it alive. I'll see if I can figure out a good way to restore it but in the meantime I would like to provide an official replacement so I can ensure it keeps working in the future.

For that I'd like to know what clj-suitable wants to do exactly. Plain eval I can easily offer and it looks like this is all thats needed?

The most basic form I can offer would be
```
(shadow.cljs.devtools.api/cljs-eval :browser "(+ 1 2 3)" {})
=> {:results ["6"], :out "", :err ""}
```

So a function that takes a build-id keyword (`:browser` is the build-id in this case) and a string of CLJS code. It just returns the results as a edn printed string. The extra map arg could take additional options, like the `:ns` things should be eval'd in.

```
(shadow.cljs.devtools.api/cljs-eval :browser "::foo" {})
=> {:results [":cljs.user/foo"], :out "", :err ""}
(shadow.cljs.devtools.api/cljs-eval :browser "::foo" {:ns 'demo.browser})
=> {:results [":demo.browser/foo"], :out "", :err ""}
```

Question would be how it should handle errors like no available JS runtime to eval against (eg. no connected browser).

This is what it would do currently but maybe it should throw?
```
(shadow.cljs.devtools.api/cljs-eval :browser "(+ 1 2 3)" {})
=> {:results [], :out "", :err "No available JS runtime.\n"}
```

Evaling multiple things is allowed. Thats why `:results` is always a vector.

```
(shadow.cljs.devtools.api/cljs-eval :browser "(require 'clojure.string) (in-ns 'clojure.string) (prn ::foo) ::bar" {})
=> {:results ["nil" "nil" "nil" ":clojure.string/bar"], :out ":clojure.string/foo\n", :err ""}
```

Would this be enough for suitable or is there anything else it needs?

One thing I saw it that it always requires an introspection-ns which I could just provide as an option.

```
(shadow.cljs.devtools.api/cljs-eval :browser "(foo.bar/something 1 2 3)" {:ensure-loaded ['foo.bar]})
```

**Comment by bbatsov** [comment]
I've disabled the offending code in cider-nrepl for the time being https://github.com/clojure-emacs/cider-nrepl/commit/ed793166f8d33a2e18939cafcc2e1951c1cc890c

**Comment by Olical** [comment]
Will disable in Conjure until there's a workaround or fix too :slightly_smiling_face: thanks for getting the word out! Was very confused at first.

**Comment by hpointu** [comment]
I've tried to play around with `shadow.cljs.devtools.api/cljs-eval` but didn't manage to integrate it to `clj-suitable`.
I must say I'm a bit confused by what is required to make this work, I'd assume this is straightforward but I must be missing something : https://github.com/hpointu/clj-suitable/commit/9cc0b5b1c8e277ec90677e5d587824a5b56d0150

**Comment by bbatsov** [comment]
@rksm Any chance you'll find time for this soon? People ask me about it from time to time and I'm not sure what to tell them. Perhaps I can ask around for some volunteer to tackle it if you're busy in the foreseeable future.

**Comment by joestrkr** [comment]
This issue is also affecting Calva users (VS Code) so a fix would be greatly appreciated.

**Comment by PEZ** [comment]
A note to [Calva](https://github.com/BetterThanTomorrow/calva) users. I just realized that this also kills **cljs** completions, if the **Calva: Enable JSCompletion** setting is on. While this issue is not resolved, disable this setting for the project.

**Comment by bbatsov** [comment]
@PEZ If someone on your team has the knowledge to fix this problem I guess we can fork the library and use the forked version for now.

**Comment by bbatsov** [comment]
@rksm Any plans to revisit this?

**Comment by rksm** [comment]
Will take a look, @mauricioszabo seems to have a fix https://github.com/mauricioszabo/repl-tooling/pull/112
