### ISSUE TITLE
Cljs completions expect a sync cljs-eval-fn

### ISSUE THREAD

**Issue by mauricioszabo** [clojure-emacs/clj-suitable#20]
I just saw that cljs-completions is inside a CLJC file, but I'm not sure if it's that useful considering that I can't imagine a way to eval cljs file synchronously. Can we somehow accept an async `cljs-eval-fn`?

I'm willing to do the change and open a PR if you accept this issue.

Thanks for this great project!

**Comment by mauricioszabo** [comment]
Ok, looking more at the problem, it seems that `suitable.js-completions` don't even work on ClojureScript. `*in*`, `*err*`, `read` and `with-in-str` don't exist in CLJS.

Was it supposed to work? Or if it don't, any reason for it to be a `.cljc` file?

**Comment by arichiardi** [comment]
Hi Mauricio, the original intent of the cljc file was to allow `lumo`/`plank` and other self-hosted tools to call into that.
I think `lumo` was indeed able to "fake" sync loading and indeed the approach was working but I don't remember now the details too much.
I don't see why we should not add a way to call things asynchronously and if I remember correctly `replumb` was doing that.

**Comment by arichiardi** [comment]
About the second issue, suitable does get some of the things it needs at runtime - however, again, sorry I don't remember all the details now and probably @rksm can help you better here.

**Comment by mauricioszabo** [comment]
Right, I think the only line I need help is this:

```
(with-in-str context (read *in* nil nil))
```

I'm not sure what's supposed to happen here (never saw this kind of code combination). It seems that it does the same thing as `clojure.tools.reader/read-string`. Is it true? If so, I can work around in CLJS :)

**Comment by vemv** [comment]
> Ok, looking more at the problem, it seems that suitable.js-completions don't even work on ClojureScript. *in*, *err*, read and with-in-str don't exist in CLJS.

I observed the same, relatedly there was no test coverage for the cljs branches of this file (much less via Lumo / Plank) so I renamed the file from .cljc to .clj in this commit https://github.com/clojure-emacs/clj-suitable/commit/599b5027ab60bc376acb8efbf78f783fe7310130#diff-6dde05b339a426e8350e927eab64ddb50929f22b9a713f42be71b7b223f06ceb

Most likely we shouldn't have WIP-ish code in the project, of course a restoring backed by tests would be welcome.
