### ISSUE TITLE
Handle string requires gracefully

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/clj-suitable#22]
## Context

https://clojurians.zulipchat.com/#narrow/stream/180378-slack-archive/topic/cider/near/251080205

## Brief

https://github.com/clojure-emacs/clj-suitable/blob/223f890ce6af23e764276c5d26303564a8cafd86/src/main/suitable/compliment/sources/cljs/analysis.cljc#L259 has a :pre that won't play fine with shadow-cljs "string requires", leading to client errors whenever one of those requires is present.

## Suggestion

If a `ns` is a string, instead of computing `(meta (clojure.core/find-ns ns))`, return `{}`.

Similar for any other place where "string requires" might be handled throughout the codebase

...Obviously, ideally clj-suitable would understand the "string requires" and offer actual functionality for them. Not sure if that's at hand though. So it seems sensible to at least avoid a hard failure.

**Comment by nwjsmith** [comment]
Just ran into this, although I'm not using shadow-cljs. [ClojureScript's Library Property Namespaces](https://clojurescript.org/news/2021-04-06-release#_library_property_namespaces) can require string requires as well.

**Comment by vemv** [comment]
Released `[org.rksm/suitable "0.4.1-alpha1"]`, feel free to try it out

**Comment by vemv** [comment]
Whoops, sorry, it's not as easy as bumping that dep isolatedly. We have to cut a cider-nrepl release that uses the new `suitable`.

**Comment by nwjsmith** [comment]
@vemv is there a way to override the version of `suitable` that `cider-nrepl` depends on in my local setup? I'd like to test this out if possible.

**Comment by vemv** [comment]
Not directly, however we can release cider-nrepl which you could refer to in cider.el

Relatedly, @bbatsov WDYT of making this defconst a defcustom instead? https://github.com/clojure-emacs/cider/blob/adfc1c940d452ace7d1dbea543024d422f60364c/cider.el#L409 Maybe we can split it into two as you mentioned earlier today.

(I'd suggest not introducing a micro breaking change with it)

**Comment by bbatsov** [comment]
Btw, constants in Elisp are not really constants - you can set this to whatever you want in your setup. And yeah - I'll likely add a defcustom for the injected cider-nrepl version.

**Comment by bbatsov** [comment]
Just made the necessary changes - see `cider-injected-middleware-version`.

**Comment by vemv** [comment]
Fix finally available in `cider-20211002.1153.tar` (i.e. today's CIDER snapshot published on MELPA) or via `[org.rksm/suitable "0.4.1"]` for other setups

@nwjsmith

**Comment by nwjsmith** [comment]
@vemv just tried it out and it's working great. Thanks for all your work on this.
