### ISSUE TITLE
Issues with `js/` completion in shadow-cljs project.

### ISSUE THREAD

**Issue by KaranAhlawat** [clojure-emacs/clj-suitable#33]
When I open a shadow-cljs based CLJS project, and then do `cider-jack-in-cljs`, selecting `shadow` and then the build (`app` in my case), everything else works fine, except for the fact that I can't seem to get `js/` completions working through CIDER.

Looking at past issues, it should be using `clj-suitable`, but I have not been able to figure out how or why it won't work.

Emacs - `29.0.92`
CIDER version - `1.8.0-snapshot`
nREPL version - `0.32.0-alpha1`
Jack-in command - `/run/user/1000/fnm_multishells/166066_1689676410315/bin/npx shadow-cljs -d nrepl/nrepl:1.0.0 -d cider/cider-nrepl:0.32.0-alpha1 -d cider/piggieback:0.5.2 server`

I'd be happy to assist in whatever way I can, and provide additional information if necessary.

**Comment by KaranAhlawat** [comment]
Hello, thanks for the quick response

1. I was getting the same error with the stable version, so I decided to update my packages and test it out. That's when I opened the issue (with the snapshots)
2. I tried it again, with a minimal project (the one provided above). Still not getting any completions, but everything else works fine.
![image](https://github.com/clojure-emacs/clj-suitable/assets/56113511/136588ad-75d5-4797-9d6d-3ce6784342c4)

**Comment by KaranAhlawat** [comment]
Yes, the page loads without any errors, and I can call `js` functions, like `(js/alert "Hi")`, which are evaluated fine, just no auto completions for those.

**Comment by KaranAhlawat** [comment]
Yes, it is.

**Comment by KaranAhlawat** [comment]
Hi, I did that. Here's the result.
![image](https://github.com/clojure-emacs/clj-suitable/assets/56113511/f331cef1-78db-4a42-8637-3b4a0f867d8f)

I will try to see if I can re-create this in a bare minimum configuration.

**Comment by KaranAhlawat** [comment]
Even in a bare config with just Cider installed (from MELPA), I see the same results as the ones posted above.

**Comment by KaranAhlawat** [comment]
I might try to dive into the code myself over the weekend.
One thing I can think is, find the function that gets called for getting JS completions, and instrument it for debugging. Then, when it's called, we could step through it and see where exactly the completions differ 🤔

**Comment by vemv** [comment]
Feel free to continue the conversation if this is still a pain point.

**Comment by dezzw** [comment]
I followed https://github.com/reducecombine/shadow-cljs-cider-demo, when I test it with cider/cider-nrepl "0.43.0", every works fine for me (js/ completion works)
<img width="1500" alt="image" src="https://github.com/clojure-emacs/clj-suitable/assets/54820344/96d5a0f3-d79e-4390-a764-2b98ef305125">
However, when I changed to "0.44.0" (even tried "0.43.1" and "0.43.3"), the completion for "js/" did not work as expected,
![CleanShot 2023-12-17 at 15 52 21@2x](https://github.com/clojure-emacs/clj-suitable/assets/54820344/e4f09ab8-aed1-4ce4-9514-9c34ef41689d)

Emacs - `29.1` (doom emacs)
CIDER version - `1.13.0-snapshot`
nREPL version - `1.0.0`
![CleanShot 2023-12-17 at 15 56 32@2x](https://github.com/clojure-emacs/clj-suitable/assets/54820344/e67fe3da-5fce-4f3b-8c9e-a81495962d61)

**Comment by vemv** [comment]
Thanks for the head up!

It's a relatively minor regression detected here https://clojurians.slack.com/archives/C0617A8PQ/p1702526959241879

I'll tackle it asap.

**Comment by KaranAhlawat** [comment]
@vemv Hey, sorry for pinging on a closed issue, but I was finally able to figure out what's wrong.
It was an emacs thing. Specifically, in the `completion-styles` variable, `cider` was not present in the list. Adding in `cider` to `completion-styles` fixes the issue so far.

**Comment by vemv** [comment]
Happy you got it!
