### ISSUE TITLE
Don't suggest properties that aren't valid code

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/clj-suitable#39]
<img width="547" alt="image" src="https://github.com/clojure-emacs/clj-suitable/assets/1162994/ae30f5c9-9928-4d47-ad7e-4adfed167fec">

`.-0` is not valid code, so it shouldn't be suggested as a completion.

(`0` is surely a property of "abc" because one can access `"abc"[0]`)

This refinement should be implemented in the most generic way possible, so that a broad selection of useless completions are trimmed away.

**Comment by rrudakov** [comment]
Just an observation. I cannot reproduce this without threading macro:

![image](https://github.com/clojure-emacs/clj-suitable/assets/6093590/1a98cbe5-9077-4d89-aa22-5ab03f9cebaa)

With threading macro I can see the problem:

![image](https://github.com/clojure-emacs/clj-suitable/assets/6093590/ab3fe0a7-54e2-402f-871c-95cd52303a24)

**Comment by vemv** [comment]
Yes, within Suitable, -> carries different implications than usual. That's because Suitable evals as parts of its completion strategy.

I reckon that we eval on `->`, which means that the `.-0` gets computed internally somewhere.

**Comment by rrudakov** [comment]
My comment regarding threading macro wasn't correct, the problem occurs in both cases. I explained the reason in the PR description.
